### ISSUE TITLE
hiding the 'add new Task' popup after creaition of a task.

### ISSUE THREAD

**Issue by anugcodes** [swarnavopramanik/task-management-application#2]
after creating a task the popup do not automatically hides. there is a  _**close**_  button but it would be better if the popup hides itself.

**Comment by swarnavopramanik** [comment]
Can you resolve this issue

**Comment by swarnavopramanik** [comment]
Please you can work the issue and tell what are change because that base I will put Contributors marks for you as per order .

**Comment by anugcodes** [comment]
> Can you resolve this issue 

Yeah I will like to solve it.

**Comment by swarnavopramanik** [comment]
Okkk

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
