### ISSUE TITLE
giving a particular height to task images.

### ISSUE THREAD

**Issue by anugcodes** [swarnavopramanik/task-management-application#3]
The images inside the task expand to original sizes, that breaks the UI and do not look good. 

![Annotation 2023-01-05 163745](https://user-images.githubusercontent.com/110781959/210766305-f9d86814-3062-4dbe-a08b-dfcb5b45f953.jpg)

**Comment by swarnavopramanik** [comment]
Yeahh that iss the one issue in my site
After create the task it not close automatically if you are manually doing
it is work but automatically not work
Kau you resolve it please it help for me you can write a code and merge it
then you check

**Comment by swarnavopramanik** [comment]
Please you can work the issue and tell what are change because that base I will put Contributors marks for you as per order .
