### ISSUE TITLE
New Task Menu stays open after saving task 

### ISSUE THREAD

**Issue by SxxAq** [swarnavopramanik/task-management-application#4]
New Task Menu stays open after saving task it needs to be closed automatically when saving a task.
I want to work on this issue.
#swoc

**Comment by swarnavopramanik** [comment]
Thank you will tell us
And please help to resolve it

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Saalim Aqueel ***@***.***>
Sent: Thursday, January 5, 2023 9:57:56 PM
To: swarnavopramanik/task-management-application ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [swarnavopramanik/task-management-application] New Task Menu stays open after saving task (Issue #4)


New Task Menu stays open after saving task it needs to be closed automatically when saving a task.
I want to work on this issue.
#swoc

**Comment by swarnavopramanik** [comment]
Please you can work the issue and tell what are change because that base I will put Contributors marks for you as per order .

**Comment by swarnavopramanik** [comment]
I think after submit task then it's aromatic closed this issue resolved I think one contributors I think resolve it you can check ones again then work ..

Thanks,
Swarnavo,
